### ISSUE TITLE
Support for converting tarballs to ext2

### ISSUE THREAD

**Issue by josch** [bestouff/genext2fs#10]
Hi,

would you accept a pull request allowing genext2fs to read a tarball (for example by using libarchive) and turn it into an ext2 image?

Even non-root users can easily create, store and manipulate tarballs containing files, directories and device nodes with arbitrary ownership, permissions, timestamps and other attributes. The interface could be as simple as:

    $ genext2fs < rootfs.tar > rootfs.img

What do you think?

**Comment by bestouff** [comment]
I love it.
