### ISSUE TITLE
Support for symbolic links in the device table

### ISSUE THREAD

**Issue by Jongy** [bestouff/genext2fs#15]
They don't exactly fit in the format current table format. But I need it to set their uid / gid (the link can be created in the source directory even if user is unprivileged, but ids can not).

I couldn't find a workaround: tried creating the link in the source directory, and adding its path as a regular file / directory /... in the device table file, but genext2fs complains (legitimately) that node types don't match.

**Comment by bestouff** [comment]
I have added the capability to change uid/gid of symlinks in bb08917741ae94714af1a8657012548f4066c8fe (3 lines of code, 40 lines of tests and comments). Could you test master and tell me if it's good for you ?

**Comment by Jongy** [comment]
Cool, I see it works and the link has the IDs I've set. But `genext2fs` emits a warning `ignoring duplicate entry` on my link, and doesn't copy the link target from the filesystem - so the generated link has no target: `s -> ''`.

I'd expect it to work like this: I can have a file/link in the directory given with `-d`, and if it has a matching line in the devices table file, that line will be used to set the inode attributes.

I recall this ^^ worked for normal files (`f`) yesterday, but it doesn't now :/ If a matching line is found in the devices table, file contents are ignored.

**Comment by bestouff** [comment]
Did you put the device file *after* the directory ? Arguments order matters.

**Comment by Jongy** [comment]
> Did you put the device file after the directory 

Hmm right, my `-D` preceded the `-d`. I swapped them and it worked now. Came back here to tell you it might be a good idea to mention that explicitly in the man page, but I see you've already done it :p The new prints in the code are also helpful.

Thanks! That's good enough for me, I'll close this.
