### ISSUE TITLE
Please support reading tarballs from stdin.

### ISSUE THREAD

**Issue by josch** [bestouff/genext2fs#20]
Thanks for accepting the libarchive pull request!

Next I'd like to be able to read tarballs from standard input. I wanted to use this issue to discuss how the interface for that should best look like. The major difference is, that when the data comes from stdin, it cannot be read twice to automatically determine how many inodes to allocate. In principle, the caller can do their own inode computations and then call genext2fs with the right `-N` argument. But maybe it makes sense for the caller to only supply the size `-b` and have the number of inodes be chosen by a heuristic if the input comes from stdin? After all, when creating an ext2 filesystem, I also only specify its size and I don't have to specify the number of inodes.

What do you think?

**Comment by bestouff** [comment]
I think I should do a more general input arguments handling, where any of them can be stdin - but then automatic sizes calculations are off the table.

**Comment by bestouff** [comment]
Is that something you really want for the next release ?

**Comment by josch** [comment]
Nope, this is just a wishlist feature. Personally I don't use genext2fs directly but from a script, so I'm fine with computing the expected number of inodes myself and passing the number to genext2fs manually via `-N`. But for somebody who wants to use genext2fs in a pipeline without having the extracted data anywhere, it would be convenient if genext2fs had some way to automatically set a sensible number of inodes based on the chosen number of blocks. I'm currently preparing a pull request that supports `-` to read from standard input but without any automatic inode computation (that's a separate issue).

**Comment by bestouff** [comment]
Implemented by #22
